apiVersion: v1
kind: Service
metadata:
  name: autobuild-svc
  labels:
    app: autobuild
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP
  selector:
      app: autobuild
